version: '3'
services:

  nginx:
    build: ./nginx
    ports:
      - 80:80
    volumes:
      - static_volume:/home/app/microservice/static
    depends_on:
      - meli-api
    restart: "on-failure"

  meli-api:
    build:
      dockerfile: ./Dockerfile
      context: ./api_meli/

    command: sh -c "python manage.py makemigrations && 
                    python manage.py migrate &&
                    python manage.py add_user &&
                    gunicorn meli.wsgi:application --bind 0.0.0.0:8000"               
    volumes:
      - .:/microservice:rw
      - static_volume:/home/app/microservice/static
      - logfile:/home/app/microservice/logs:rw
    env_file:
      - ./api_meli/.env
    image: meli-api

    expose:
      - 8000

    restart: "on-failure"

volumes:
  static_volume:
  logfile:













